"""Offline browser and simulated-native-transport tests. NOT a macOS/PPT test."""
from pathlib import Path
import json, os, re
from playwright.sync_api import sync_playwright, Error as PlaywrightError
ROOT=Path(__file__).resolve().parents[1]
WORK=ROOT/'Tests'
HTML=(ROOT/'Source/reader.html').read_text()
results=[]
def check(name,condition):
    if not condition: raise AssertionError(name)
    results.append({'test':name,'result':'PASS'})
    print('PASS',name,flush=True)
STORAGE="""Object.defineProperty(window,'localStorage',{value:{data:{},getItem(k){return this.data[k]??null},setItem(k,v){this.data[k]=String(v)},removeItem(k){delete this.data[k]}}});"""
with sync_playwright() as p:
    b=p.chromium.launch(headless=True, executable_path=os.environ.get('CHROMIUM_EXECUTABLE'), args=['--no-sandbox'])
    ctx=b.new_context(viewport={'width':1180,'height':850},accept_downloads=True)
    ctx.set_offline(True)
    errors=[]; requests=[]
    def page(native=False):
        q=ctx.new_page(); q.set_default_timeout(3500)
        q.on('pageerror',lambda e:errors.append(str(e)))
        q.on('request',lambda r:requests.append(r.url) if r.url.startswith(('https://','http://')) else None)
        q.on('dialog',lambda d:d.accept())
        q.evaluate(STORAGE)
        if native:q.evaluate('window.nativeMessages=[]; window.webkit={messageHandlers:{companion:{postMessage:m=>nativeMessages.push(m)}}};')
        q.set_content(HTML)
        q.evaluate("document.getElementById('settingsPanel').open=true")
        if native:q.evaluate("Companion.receive({type:'ready'})")
        return q
    q=page()
    d=lambda:q.evaluate('Companion.diagnostics()')
    check('Offline render: four example slides and one current line',d()['slides']==4 and q.locator('.current').count()==1)
    check('Browser has no live PowerPoint controls',all(q.locator('#'+i).is_disabled() for i in ['linkBtn','refreshNotesBtn','arrowModeBtn']))
    q.locator('#reader').focus();q.keyboard.press('ArrowDown')
    check('Down moves exactly one line, not slide',d()['line']==1 and d()['slide']==1)
    q.keyboard.press('ArrowUp');check('Up moves one line backwards',d()['line']==0 and d()['slide']==1)
    q.keyboard.press('ArrowUp');check('Up stops at first line',d()['line']==0 and d()['slide']==1)
    q.keyboard.press('End');q.keyboard.press('ArrowDown');q.keyboard.press('ArrowDown')
    check('Down at final line never changes slide',d()['line']==2 and d()['slide']==1)
    q.keyboard.press('ArrowRight');check('Right moves to next script slide, line 1',d()['slide']==2 and d()['line']==0)
    q.keyboard.press('ArrowDown');q.keyboard.press('ArrowLeft');check('Left restores the previous slide saved line',d()['slide']==1 and d()['line']==2)
    q.keyboard.press('ArrowLeft');check('Left stops at first slide',d()['slide']==1)
    q.keyboard.press('PageDown');check('Page Down restores next slide position',d()['slide']==2 and d()['line']==1)
    before=d();q.evaluate("document.getElementById('reader').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',repeat:true,bubbles:true,cancelable:true}))")
    check('Held-arrow repeat is suppressed',d()['slide']==before['slide'])
    q.locator('#editBtn').click();q.locator('#scriptInput').focus();before=d();q.keyboard.press('ArrowRight');q.keyboard.press('ArrowDown')
    check('Editor arrow keys do not navigate reader',d()['slide']==before['slide'] and d()['line']==before['line'])
    q.locator('#scriptInput').fill('# Slide 1 — A\nHello\n# Slide 1 — B\nAgain');q.locator('#applyBtn').click()
    check('Duplicate script slide numbers rejected','unique' in q.locator('#editorError').inner_text())
    q.locator('#cancelEditBtn').click()
    q.locator('#fileInput').set_input_files({'name':'test_notes.pptx','mimeType':'application/vnd.openxmlformats-officedocument.presentationml.presentation','buffer':(WORK/'test_notes.pptx').read_bytes()})
    q.wait_for_timeout(500)
    check('PPTX notes imported in deck order',q.locator('.words').all_text_contents()==['Good morning.','Thank you for coming.','Let’s begin.'])
    check('Imported total includes a slide without notes',d()['slides']==3 and '3' in q.locator('#slideEyebrow').inner_text())
    q.locator('#reader').focus();q.keyboard.press('ArrowRight')
    check('Blank notes slide stays in place and has no line highlight',d()['slide']==2 and q.locator('.empty').count()==1 and q.locator('.current').count()==0)
    q.keyboard.press('ArrowRight')
    check('Unicode and XML-looking notes are safe text',q.locator('.words').all_text_contents()==['A < B & C > D.','Pause.','下一行 — café 🚀'])
    q.keyboard.press('ArrowRight');check('Right stops at last slide',d()['slide']==3)
    q.locator('#nextLineBtn').click();q.wait_for_timeout(350)
    stored=q.evaluate("JSON.parse(localStorage.getItem('scriptCompanion.v1'))")
    check('Snapshot autosave retains slide, line and structured notes',stored['slide']==2 and stored['line']==1 and len(stored['deckSlides'])==3)
    with q.expect_download() as dl:q.locator('#backupBtn').click()
    dl.value.save_as(str(WORK/'backup.json'))
    saved=json.loads((WORK/'backup.json').read_text())
    check('Backup includes Unicode notes and line position','下一行' in saved['raw'] and saved['line']==1)
    q.locator('#fileInput').set_input_files({'name':'saved.json','mimeType':'application/json','buffer':json.dumps(saved).encode()})
    q.wait_for_timeout(100);check('Structured backup restores reader position',d()['slide']==3 and d()['line']==1)
    # Native web transport is deliberately mocked. This verifies protocol/UI only.
    n=page(native=True)
    nd=lambda:n.evaluate('Companion.diagnostics()')
    send=lambda event:n.evaluate('e=>Companion.receive(e)',event)
    def row(i,text,title=None,ok=True,id=None):
        return {'number':i,'id':id or f'id-{i}','title':title or f'Topic {i}','notes':text,'notesOK':ok,'notesError':'' if ok else 'Notes body unavailable.'}
    deck=[row(1,'Opening sentence.\rSecond line.\vThird line.'),row(2,'The problem.\nOne more thought.\nA final point.'),row(3,''),row(4,'Thank you.\nQuestions?')]
    def payload(num,rows=deck,total=None,current=None,**kwargs):
        return {'type':'slide','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx','number':num,'total':total or len(rows),'current':current or rows[num-1],**kwargs}
    check('Native bridge announces readiness',n.evaluate("nativeMessages.some(m=>m.type==='ready')"))
    send({'type':'linked','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx'});send(payload(2,slides=deck))
    check('Live deck replaces unrelated example script with actual notes',nd()['slide']==2 and n.locator('.words').all_text_contents()==['The problem.','One more thought.','A final point.'])
    check('Slide counter shows current and total from native state','Slide 2 / 4' in n.locator('#connectionStatus').inner_text())
    n.locator('#reader').focus();before=n.evaluate("nativeMessages.filter(m=>m.type==='powerPointStep').length");n.keyboard.press('ArrowDown')
    check('Live Down only highlights a line, no PowerPoint command',nd()['line']==1 and n.evaluate("nativeMessages.filter(m=>m.type==='powerPointStep').length")==before)
    current_node=n.locator('.current');n.evaluate('window.keptLine=document.querySelector(".current")');send(payload(2))
    check('Unchanged live poll keeps highlighted sentence and DOM node',nd()['line']==1 and n.evaluate('window.keptLine===document.querySelector(".current")'))
    n.keyboard.press('ArrowRight')
    check('Right sends one next-slide request without optimistic slide change',nd()['slide']==2 and n.evaluate("nativeMessages.filter(m=>m.type==='powerPointStep'&&m.direction==='next').length")==1)
    before=nd()['line'];n.keyboard.press('ArrowDown');check('Line movement pauses during slide navigation',nd()['line']==before)
    send(payload(3));check('Actual slide change resets highlight and clears notes for blank slide',nd()['slide']==3 and nd()['line']==0 and n.locator('.current').count()==0 and 'no speaker notes' in n.locator('.empty').inner_text())
    n.locator('#reader').focus();n.keyboard.press('ArrowLeft');check('Left sends previous-slide command',n.evaluate("nativeMessages.some(m=>m.type==='powerPointStep'&&m.direction==='previous')"))
    send(payload(1));check('Live carriage returns and soft breaks split into three lines',n.locator('.words').all_text_contents()==['Opening sentence.','Second line.','Third line.'])
    n.locator('#reader').focus();n.keyboard.press('ArrowDown')
    updated=row(1,'New first line.\nOpening sentence.\nSecond line.\nThird line.')
    send(payload(1,current=updated))
    check('Edited live notes preserve the highlighted sentence when found',nd()['line']==2 and n.locator('.current .words').inner_text()=='Second line.')
    n.keyboard.press('End');n.keyboard.press('ArrowDown');check('Live Down at last line never requests next slide',nd()['slide']==1 and nd()['line']==3)
    send(payload(1,current=row(1,'A different slide now.',id='new-id')))
    check('A different slide ID at the same index resets highlight',nd()['line']==0 and n.locator('.words').inner_text()=='A different slide now.')
    deck5=deck+[row(5,'A newly added slide.')];send(payload(5,rows=deck5,total=5,current=deck5[4]))
    check('Changed total creates missing slide and follows it',nd()['slides']==5 and nd()['slide']==5 and nd()['liveTotal']==5)
    check('Last live slide disables forward slide button',n.locator('#nextSlideBtn').is_disabled())
    send(payload(1,total=2,current=deck[0]));check('Reduced total removes excess slides',nd()['slides']==2 and nd()['liveTotal']==2)
    failed=row(2,'DO NOT SHOW STALE TEXT',ok=False);send(payload(2,total=2,current=failed))
    check('Notes-read failure clears text rather than showing stale script',not n.locator('.words').count() and 'unavailable' in n.locator('.empty').inner_text().lower())
    odd=row(2,'# Slide 99 — This is spoken text\n<script>unsafe()</script>\nCafé 中文 👋')
    send(payload(2,total=2,current=odd))
    check('Heading-like notes do not create phantom slides',nd()['slides']==2 and n.locator('.words').first.inner_text().startswith('# Slide 99'))
    check('Live notes are text, not executable HTML',n.locator('#reader script').count()==0 and n.locator('.words').nth(1).inner_text()=='<script>unsafe()</script>')
    check('Successful notes update clears earlier failure notice',n.locator('#notice').is_hidden())
    n.locator('#refreshNotesBtn').click();check('Refresh asks native app to reread all notes',n.evaluate("nativeMessages.some(m=>m.type==='refreshNotes')"))
    send({'type':'busy','message':'Reading all PowerPoint speaker notes…'});send(payload(2,total=2,current=odd))
    check('Successful update clears transient reading notice',n.locator('#notice').is_hidden() and not nd()['busy'])
    n.locator('#arrowModeBtn').click();check('Presentation-key capture requires explicit native opt-in',n.evaluate("nativeMessages.some(m=>m.type==='toggleArrowMode')") and not nd()['arrowMode'])
    send({'type':'arrowMode','enabled':True});check('UI accurately shows enabled native arrow mode',nd()['arrowMode'] and 'On' in n.locator('#arrowModeBtn').inner_text())
    n.locator('#reader').focus();n.keyboard.press('Escape');check('Escape requests release of global arrow keys',n.evaluate("nativeMessages.some(m=>m.type==='disableArrowMode')"))
    n.locator('#helpBtn').click();n.wait_for_timeout(100);check('Native is told to suspend controls while help is open',n.evaluate("nativeMessages.some(m=>m.type==='interaction'&&m.blocked===true)"));n.locator('#closeHelpBtn').click()
    send({'type':'unlinked','message':'Connection lost. Last notes are a snapshot.'})
    check('Disconnect visibly restores snapshot mode and turns capture off',not nd()['following'] and not nd()['arrowMode'] and n.locator('#editBtn').is_enabled())
    n.locator('#editBtn').click();n.locator('#applyBtn').click()
    check('Live heading-like notes survive round trip through manual editor',nd()['slides']==2 and n.locator('#editor').evaluate('e=>!e.open'))
    # Invalid native packet must not display a different slide's notes.
    send({'type':'linked','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx'});send(payload(1,slides=deck))
    previous=n.locator('.words').all_text_contents();send(payload(2,current=deck[0]))
    check('Mismatched notes packet is rejected and requests unlink',n.locator('.words').all_text_contents()==previous and n.evaluate("nativeMessages.some(m=>m.type==='unlink')"))
    send({'type':'unlinked','message':'Test finished.'})
    send({'type':'linked','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx'})
    repeated=row(1,'Pause.\nA sentence.\nPause.\nFinish.')
    send(payload(1,current=repeated));n.locator('#restartLineBtn').click()
    n.locator('#reader').focus();n.keyboard.press('ArrowDown');n.keyboard.press('ArrowDown');send(payload(1,current=repeated))
    check('Repeated identical speaking lines keep their exact position on polling',nd()['line']==2 and n.locator('.current').get_attribute('data-line')=='2')
    send({'type':'unlinked','message':'Snapshot.'})
    # Layout: use a simulated live deck, label screenshots as protocol previews in docs.
    send({'type':'linked','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx'});send(payload(2,slides=deck));n.locator('#restartLineBtn').click();n.locator('#nextLineBtn').click()
    for w,h in [(1180,850),(660,600),(390,844)]:
        n.set_viewport_size({'width':w,'height':h});n.wait_for_timeout(200)
        check(f'No horizontal overflow at {w}×{h}',n.evaluate('document.documentElement.scrollWidth <= innerWidth'))
        n.screenshot(path=str(WORK/f'layout_{w}.png'));area=n.locator('#reader').bounding_box();print('Reader height:',area['height'],flush=True);check(f'Reader has visible height at {w}×{h}',area['height']>=120)
    n.set_viewport_size({'width':1180,'height':850});n.wait_for_timeout(350);n.screenshot(path=str(WORK/'sync_preview.png'))
    n.set_viewport_size({'width':660,'height':600});n.locator('#compactBtn').click();n.wait_for_timeout(350);n.screenshot(path=str(WORK/'sync_compact.png'))
    check('Exactly one live line stays highlighted',n.locator('.current').count()==1)
    # Some locked-down test environments prohibit local-file navigation.
    # Report that restriction instead of weakening policy or claiming it passed.
    try:
        f=ctx.new_page();f.on('pageerror',lambda e:errors.append(str(e)));f.goto((ROOT/'Source/reader.html').as_uri())
        check('Self-contained reader opens from a real local file while offline',f.locator('#slideSelect option').count()==4)
        f.locator('#reader').focus();f.keyboard.press('ArrowDown');f.wait_for_timeout(400);f.reload()
        check('Real file-origin storage restores the selected line after reload',f.evaluate('Companion.diagnostics().line')==1)
    except PlaywrightError as exc:
        if 'ERR_BLOCKED_BY_ADMINISTRATOR' not in str(exc): raise
        results.append({'test':'Actual file-URL launch and real file-origin storage', 'result':'NOT RUN', 'reason':'This test environment blocks file URLs by policy. No policy bypass attempted.'})
        print('NOT RUN actual file-URL launch/storage: blocked by test-environment policy.',flush=True)
    check('No external network requests',not requests)
    check('No browser JavaScript errors',not errors)
    b.close()
(WORK/'results.json').write_text(json.dumps({'environment':'Linux Chromium; simulated native transport, not PowerPoint','checks':results},indent=2))
print(f"{sum(r['result']=='PASS' for r in results)} checks passed; {sum(r['result']!='PASS' for r in results)} not run. Native macOS / PowerPoint execution remains untested.")
