"""0.5 UI tests: real bundled JS + virtual clock + simulated native packets.
Not a macOS build, PowerPoint, AX keyboard delivery, or real file-origin test.
"""
from pathlib import Path
import json, os
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[1]
HTML=(R/'Source/reader.html').read_text()
checks=[]; errors=[]; requests=[]
def check(name, value):
    assert value, name
    checks.append({'test':name,'result':'PASS'}); print('PASS',name,flush=True)
with sync_playwright() as pw:
    b=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE'),headless=True,args=['--no-sandbox'])
    ctx=b.new_context(viewport={'width':1180,'height':850},locale='en-GB',timezone_id='Europe/London')
    ctx.set_offline(True)
    def new(native=False, stored=None):
        p=ctx.new_page();p.set_default_timeout(3000)
        p.on('pageerror',lambda e:errors.append(str(e)))
        p.on('request',lambda r:requests.append(r.url) if r.url.startswith(('http://','https://')) else None)
        p.clock.install(time=__import__('datetime').datetime(2026,9,16,9,0,0,tzinfo=__import__('datetime').timezone.utc))
        p.evaluate("Object.defineProperty(window,'localStorage',{value:{data:{},getItem(k){return this.data[k]??null},setItem(k,v){this.data[k]=String(v)},removeItem(k){delete this.data[k]}}});")
        if stored:p.evaluate('obj=>Object.assign(localStorage.data,obj)',stored)
        if native:p.evaluate('window.nativeMessages=[];window.webkit={messageHandlers:{companion:{postMessage:m=>nativeMessages.push(m)}}};')
        p.set_content(HTML)
        if native:p.evaluate("Companion.receive({type:'ready'})")
        p.clock.run_for(30)
        return p
    p=new();d=lambda:p.evaluate('Companion.diagnostics()')
    check('Timer opens ready and at zero',not d()['timerRunning'] and d()['elapsedMs']==0 and p.locator('#timerState').inner_text()=='READY')
    check('Clock and elapsed timer are separate',p.locator('#clockTime').inner_text()!=p.locator('#elapsedTime').inner_text())
    p.locator('#timerToggleBtn').click();p.clock.run_for(3200)
    check('Start counts elapsed time',d()['timerRunning'] and 3190<=d()['elapsedMs']<3500)
    check('Large display uses hours minutes seconds',p.locator('#elapsedTime').inner_text()=='00:00:03')
    p.locator('#reader').focus();p.keyboard.press('ArrowDown');p.keyboard.press('ArrowDown');p.keyboard.press('ArrowRight');p.clock.run_for(2200)
    check('Slide changes do not reset total timer',d()['slide']==2 and d()['elapsedMs']>=5300)
    check('Current slide has its own time',2100<=d()['slideElapsedMs']<2500)
    p.keyboard.press('ArrowLeft');p.clock.run_for(1100)
    check('Return restores the highlighted line',d()['slide']==1 and d()['line']==2)
    check('Return adds to that slide’s earlier time',4200<=d()['slideElapsedMs']<4800)
    p.locator('#timerToggleBtn').click();frozen=d()['elapsedMs'];p.clock.run_for(5000)
    check('Pause excludes paused time',not d()['timerRunning'] and d()['elapsedMs']==frozen)
    check('Paused UI offers Resume',p.locator('#timerToggleBtn').inner_text()=='Resume timer')
    p.locator('#reader').focus();p.keyboard.press('t');p.clock.run_for(1200);p.keyboard.press('t')
    check('T toggles timer without changing line',not d()['timerRunning'] and d()['line']==2 and d()['elapsedMs']>=frozen+1100)
    p.once('dialog',lambda dialog:dialog.dismiss());p.locator('#timerResetBtn').click()
    check('Cancel reset preserves elapsed time',d()['elapsedMs']>0)
    p.once('dialog',lambda dialog:dialog.accept());p.locator('#timerResetBtn').click()
    check('Reset clears total and per-slide time',d()['elapsedMs']==0 and d()['slideElapsedMs']==0 and not d()['timerRunning'])
    check('Reset does not reset the highlighted line',d()['slide']==1 and d()['line']==2)
    p.locator('#editBtn').click();p.locator('#scriptInput').focus();p.keyboard.press('t')
    check('Typing T in the editor does not run the timer',not d()['timerRunning'])
    p.locator('#cancelEditBtn').click()
    p.locator('#timerToggleBtn').click();p.clock.run_for(6200)
    check('Running timer checkpoints separately from notes',p.evaluate('Number(JSON.parse(localStorage.getItem("scriptCompanion.timer.v1")).elapsedMs)')>=5000)
    p.locator('#timerToggleBtn').click();saved=p.evaluate('({...localStorage.data})');r=new(stored=saved);rd=r.evaluate('Companion.diagnostics()')
    check('Reopened browser state restores the elapsed value paused',rd['elapsedMs']>=6100 and not rd['timerRunning'])
    r.clock.run_for(5000);check('Closed/paused reader time is not added on restore',r.evaluate('Companion.diagnostics().elapsedMs')==rd['elapsedMs'])
    # Full JSON backup includes the latest timing and per-slide highlight positions.
    p.on('dialog',lambda dialog:dialog.accept())
    with p.expect_download() as download:p.locator('#backupBtn').click()
    download.value.save_as(str(R/'Tests/timer_backup.json'))
    backup=json.loads((R/'Tests/timer_backup.json').read_text())
    check('Backup includes elapsed time and per-slide times',backup['timer']['elapsedMs']>=6100 and len(backup['timer']['slides'])>=1)
    r.on('dialog',lambda dialog:dialog.accept());r.locator('#fileInput').set_input_files(str(R/'Tests/timer_backup.json'));r.clock.run_for(400)
    check('Backup restore preserves highlighted line and paused timing',r.evaluate('Companion.diagnostics().line')==2 and not r.evaluate('Companion.diagnostics().timerRunning'))
    # Simulate a native link and use sparse position packets (the 0.5 fast protocol).
    n=new(native=True);nd=lambda:n.evaluate('Companion.diagnostics()');send=lambda event:n.evaluate('event=>Companion.receive(event)',event)
    rows=[{'number':i,'id':str(255+i),'title':f'Lesson {i}','notes':f'Opening thought for slide {i}.\nThe important detail.\nMy conclusion.','notesOK':True} for i in range(1,4)]
    send({'type':'linked','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx'})
    send({'type':'slide','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx','number':1,'total':3,'current':rows[0],'slides':rows})
    fast=lambda i,**kw:{'type':'slide','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx','number':i,'total':3,'slideID':str(255+i),'positionOnly':True,'navigationAvailable':True,**kw}
    n.locator('#reader').focus();n.keyboard.press('ArrowDown');n.keyboard.press('ArrowDown')
    n.evaluate('window.originalLine=document.querySelector(".current");')
    for _ in range(25):send(fast(1))
    check('Repeated fast polls keep the same highlighted DOM node',n.evaluate('originalLine===document.querySelector(".current")'))
    check('Repeated fast polls preserve the line number',nd()['line']==2)
    n.locator('#timerToggleBtn').click();n.clock.run_for(2200);send(fast(2));n.clock.run_for(1200)
    check('Fast confirmed slide change uses cached notes',nd()['slide']==2 and 'slide 2' in n.locator('.words').first.inner_text())
    check('Fast slide changes do not stop timing',nd()['timerRunning'] and nd()['elapsedMs']>=3300)
    send(fast(1));check('Fast return restores the previous line',nd()['line']==2)
    # A request is not a confirmation. Clock/timer continue while awaiting PowerPoint.
    n.locator('#nextSlideBtn').click();current=nd()['slide'];n.clock.run_for(1500)
    check('Requested slide does not optimistically change notes',nd()['busy'] and nd()['slide']==current)
    check('Timer continues during PowerPoint verification',nd()['elapsedMs']>=4800)
    sent=n.evaluate('nativeMessages.filter(m=>m.type==="powerPointStep").length')
    n.locator('#reader').focus();n.keyboard.press('ArrowRight')
    check('Busy reader does not send a duplicate slide shortcut',n.evaluate('nativeMessages.filter(m=>m.type==="powerPointStep").length')==sent)
    send(fast(2));send({'type':'navigationResult','ok':True,'message':'Simulated confirmation.'})
    check('Confirmation unblocks slide controls',not nd()['busy'] and n.locator('#nextSlideBtn').is_enabled())
    send(fast(2,slideID='new-reordered-id'))
    check('Different slide ID never reuses another slide’s notes',n.locator('.empty').count()==1 and not nd()['notesOK'])
    replacement={**rows[1],'id':'new-reordered-id','notes':'Fresh notes after reorder.\nVerified text.'}
    send({'type':'slide','name':'Rehearsal.pptx','identity':'/local/Rehearsal.pptx','number':2,'total':3,'current':replacement})
    check('Full notes read replaces pending placeholder',nd()['notesOK'] and n.locator('.words').first.inner_text()=='Fresh notes after reorder.')
    send({'type':'unlinked','message':'Snapshot mode.'});before=nd()['elapsedMs'];n.clock.run_for(1000)
    check('Unlink leaves elapsed timer running until paused',nd()['timerRunning'] and nd()['elapsedMs']>=before+900)
    check('Native timer checkpoint uses dedicated small messages',n.evaluate('nativeMessages.some(m=>m.type==="saveTimer"&&m.timer&&!m.state)'))
    # New native ready data cannot silently start an old timer.
    other=new(native=True);other.evaluate("Companion.receive({type:'ready',timer:{elapsedMs:65000,slides:{}}})")
    check('Native saved timer restores paused with HH:MM:SS',not other.evaluate('Companion.diagnostics().timerRunning') and other.locator('#elapsedTime').inner_text()=='00:01:05')
    invalid=new(stored={'scriptCompanion.timer.v1':json.dumps({'elapsedMs':-100,'slides':{'bad':-8}})})
    check('Invalid saved time is clamped safely',invalid.evaluate('Companion.diagnostics().elapsedMs')==0)
    # All viewport layouts: script always first, current line at the upper reading edge.
    # Open/closed setup and compact mode use the same reading layout.
    for width,height in [(1180,850),(920,700),(660,540),(520,700),(390,844)]:
        r.set_viewport_size({'width':width,'height':height})
        r.evaluate('document.getElementById("settingsPanel").open=false;document.querySelector("footer").scrollTop=0;')
        r.locator('#reader').focus();r.keyboard.press('Home');r.clock.run_for(50)
        a=r.locator('.current').bounding_box();read=r.locator('#reader').bounding_box();prev=r.locator('#previewPane').bounding_box();el=r.locator('#elapsedTime').bounding_box()
        check(f'Notes above preview and timer at {width}',a['y']<prev['y'] and a['y']<el['y'])
        check(f'Current line anchored near reading top at {width}',abs(a['y']-read['y']-4)<3 and a['y']<85)
        check(f'Usable notes height at {width}',read['height']>=160)
        check(f'No horizontal overflow at {width}',r.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        r.screenshot(path=str(R/f'Tests/notes_first_{width}.png'))
    r.set_viewport_size({'width':660,'height':540});r.locator('#compactBtn').click();r.clock.run_for(50)
    check('Compact keeps notes above preview',r.locator('#reader').bounding_box()['y']<r.locator('#previewPane').bounding_box()['y'])
    r.locator('#reader').focus();r.keyboard.press('End');r.clock.run_for(50)
    check('Last line also aligns at top, not the bottom',abs(r.locator('.current').bounding_box()['y']-r.locator('#reader').bounding_box()['y']-4)<3)
    r.keyboard.press('p');r.clock.run_for(50)
    check('Hiding preview does not hide timer or clock',not r.locator('#previewPane').is_visible() and r.locator('#elapsedTime').is_visible() and r.locator('#clockTime').is_visible())
    check('No JavaScript exceptions',not errors)
    check('No external requests',not requests)
    b.close()
(R/'Tests/timer_layout_results.json').write_text(json.dumps({'environment':'Offline Linux Chromium; virtual elapsed time; native packets simulated','checks':checks},indent=2))
print(len(checks),'notes-first/timer/sparse-protocol checks passed.')
